"""changed some booleans to is_ format

Revision ID: 5ec4ac515b7f
Revises: ef1e6f98c860
Create Date: 2020-11-14 05:42:27.842504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ec4ac515b7f'
down_revision = 'ef1e6f98c860'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('board', sa.Column('is_public', sa.Boolean(), nullable=False))
    op.drop_column('board', 'public')
    op.add_column('match', sa.Column('is_verified', sa.Boolean(), nullable=False))
    op.drop_column('match', 'verified')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match', sa.Column('verified', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('match', 'is_verified')
    op.add_column('board', sa.Column('public', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('board', 'is_public')
    # ### end Alembic commands ###
