"""changed rating to support ties

Revision ID: ef1e6f98c860
Revises: ec01a892620b
Create Date: 2020-11-13 23:50:18.715998

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ef1e6f98c860'
down_revision = 'ec01a892620b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match', sa.Column('from_user_rating_change', sa.Float(), nullable=False))
    op.add_column('match', sa.Column('to_user_rating_change', sa.Float(), nullable=False))
    op.drop_column('match', 'winner_rating_change')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match', sa.Column('winner_rating_change', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('match', 'to_user_rating_change')
    op.drop_column('match', 'from_user_rating_change')
    # ### end Alembic commands ###
